"""add sample input to puzzles

Revision ID: 309be8116dbb
Revises: 65e50b44c2a8
Create Date: 2026-05-22 10:38:47.704116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '309be8116dbb'
down_revision: Union[str, Sequence[str], None] = '65e50b44c2a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puzzles', sa.Column('sample_input', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puzzles', 'sample_input')
    # ### end Alembic commands ###
