"""add deferred start and accepted testcase

Revision ID: a917728937fc
Revises: 309be8116dbb
Create Date: 2026-05-23 14:16:04.514089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a917728937fc'
down_revision: Union[str, Sequence[str], None] = '309be8116dbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puzzle_plays', sa.Column('accepted_testcase', sa.Text(), nullable=True))
    op.alter_column('puzzle_plays', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('puzzle_plays', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('puzzle_plays', 'accepted_testcase')
    # ### end Alembic commands ###
