"""add anonymous play state

Revision ID: f32e2cda03b0
Revises: a082f79249be
Create Date: 2026-05-21 14:57:47.476224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f32e2cda03b0'
down_revision: Union[str, Sequence[str], None] = 'a082f79249be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitor_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitor_sessions_token_hash'), 'visitor_sessions', ['token_hash'], unique=True)
    op.create_table('puzzle_plays',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visitor_session_id', sa.UUID(), nullable=False),
    sa.Column('puzzle_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('solved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzles.id'], ),
    sa.ForeignKeyConstraint(['visitor_session_id'], ['visitor_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visitor_session_id', 'puzzle_id')
    )
    op.create_index(op.f('ix_puzzle_plays_puzzle_id'), 'puzzle_plays', ['puzzle_id'], unique=False)
    op.create_index(op.f('ix_puzzle_plays_visitor_session_id'), 'puzzle_plays', ['visitor_session_id'], unique=False)
    op.create_table('puzzle_stats',
    sa.Column('puzzle_id', sa.UUID(), nullable=False),
    sa.Column('solve_count', sa.Integer(), nullable=False),
    sa.Column('total_attempts', sa.Integer(), nullable=False),
    sa.Column('total_solve_seconds', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzles.id'], ),
    sa.PrimaryKeyConstraint('puzzle_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puzzle_stats')
    op.drop_index(op.f('ix_puzzle_plays_visitor_session_id'), table_name='puzzle_plays')
    op.drop_index(op.f('ix_puzzle_plays_puzzle_id'), table_name='puzzle_plays')
    op.drop_table('puzzle_plays')
    op.drop_index(op.f('ix_visitor_sessions_token_hash'), table_name='visitor_sessions')
    op.drop_table('visitor_sessions')
    # ### end Alembic commands ###
